/* ----------------------------------------------------------------------
! ----------------------------------------------------------------------
! Slow manifolds computation in the Tran system 
! ----------------------------------------------------------------------
! C o m p.  o f  t h e  a t t r a c t i n g  s l o w  m a n i f o l d   
! ----------------------------------------------------------------------
! Homotopy step 1: "away from the folded node along the fold curve"
! followed by
! Homotopy step 2: "away from the fold curve on the critical manifold"
! followed by
! Actual computation of the attracting slow manifold
! ----------------------------------------------------------------------
! (Ref.: Desroches, Krauskopf and Osinga, CHAOS 18, 015107 (2008))        
! ----------------------------------------------------------------------
! --------------------------------------------------------------------*/

/*
 *  Luofixedpoints_av.c
 *
 *  AUTO C file for the vector field named: Luofixedpoints
 *
 *  This file was generated by the program VFGEN, version: 2.5.0
 *  Generated on 11-Jan-2019 at 16:28
 */

#include <math.h>
#include "auto_f2c.h"

/*
 *  FUNC  Defines the vector field and its derivatives
 */

int func(integer ndim_, const doublereal *u_, const integer *icp_,
         const doublereal *par_, integer ijac_,
         doublereal *f_, doublereal *dfdu_, doublereal *dfdp_)
{
    integer dfdu__dim1, dfdp__dim1;
    const double Ki = 145.0;
    const double Nao = 140.0;
    const double Nai = 18.0;
    const double PRNaK = 1.8329999999999999e-02;
    const double R = 8.3144626181532395e+00;
    const double Kelvin = 3.1014999999999998e+02;
    const double Faraday = 9.6485332900000003e+01;
    const double cda = 9.5000000000000001e-02;
    const double cdb = 7.0000000000000007e-02;
    const double cfa = 1.2000000000000000e-02;
    const double cfb = 6.4999999999999997e-03;
    const double cxa = 5.0000000000000001e-04;
    const double cxb = 1.2999999999999999e-03;
    const double cxi = 2.8370000000000002e+00;
    const double cK1a = 1.0200000000000000e+00;
    const double cK1b = 4.9124000000000001e-01;
    const double Vda = -5.0000000000000000e+00;
    const double Vdb = 4.4000000000000000e+01;
    const double Vfa = 2.8000000000000000e+01;
    const double Vfb = 3.0000000000000000e+01;
    const double Vxa = 5.0000000000000000e+01;
    const double Vxb = 2.0000000000000000e+01;
    const double Vxi1 = 7.7000000000000000e+01;
    const double Vxi2 = 3.5000000000000000e+01;
    const double sda1 = -1.0000000000000000e-02;
    const double sda2 = -7.1999999999999995e-02;
    const double sdb1 = -1.7000000000000001e-02;
    const double sdb2 = 5.0000000000000003e-02;
    const double sfa1 = -8.0000000000000002e-03;
    const double sfa2 = 1.4999999999999999e-01;
    const double sfb1 = -2.0000000000000000e-02;
    const double sfb2 = -2.0000000000000001e-01;
    const double sxa1 = 8.3000000000000004e-02;
    const double sxa2 = 5.7000000000000002e-02;
    const double sxb1 = -5.9999999999999998e-02;
    const double sxb2 = -4.0000000000000001e-02;
    const double sxi = 4.0000000000000001e-02;
    const double sK1a = 2.3849999999999999e-01;
    const double sK1b1 = 8.0320000000000003e-02;
    const double sK1b2 = 6.1749999999999999e-02;
    const double sK1b3 = -5.1429999999999998e-01;
    const double sKp = 1.6722408026755853e-01;
    const double gK1w = 6.0470000000000002e-01;
    const double gKp = 1.8300000000000000e-02;
    const double gb = 3.9210000000000002e-02;
    const double VKp = 7.4880000000000004e+00;
    const double Vb = 5.9869999999999997e+01;
    double V, d, f, x;
    double C, Ko, shiftd, shiftf, gKw, gCa, VCa, T;
    double gK, gK1, VK, VK1, alphad_inf, betad_inf, alphad_tau, betad_tau, alphaf_inf, betaf_inf, alphaf_tau, betaf_tau, alphax, betax, taud, tauf, taux, dinf, finf, xinf, xi, alphaK1, betaK1, K1inf, Kp, ICa, IK, IK1, IKp, Ib, A;

    dfdu__dim1 = ndim_;
    dfdp__dim1 = ndim_;

    V          = u_[0];
    d          = u_[1];
    f          = u_[2];
    x          = u_[3];

    C          = par_[0];
    Ko         = par_[1];
    shiftd     = par_[2];
    shiftf     = par_[3];
    gKw        = par_[4];
    gCa        = par_[5];
    VCa        = par_[6];
    T          = par_[10];

    gK = 4.3033148291193524e-01*gKw*pow(Ko,(1.0/2.0));
    gK1 = 4.3033148291193524e-01*pow(Ko,(1.0/2.0))*gK1w;
    VK = 1.0/Faraday*log(( PRNaK*Nao+Ko)/( Ki+PRNaK*Nai))*R*Kelvin;
    VK1 = 1.0/Faraday*R*log(1.0/Ki*Ko)*Kelvin;
    alphad_inf = cda/( exp(sda2*( Vda-shiftd+V))+1.0)*exp(sda1*( Vda-shiftd+V));
    betad_inf = 1.0/( exp(( Vdb-shiftd+V)*sdb2)+1.0)*exp(( Vdb-shiftd+V)*sdb1)*cdb;
    alphad_tau = exp(( Vda+V)*sda1)/( exp(sda2*( Vda+V))+1.0)*cda;
    betad_tau = 1.0/( exp(sdb2*( Vdb+V))+1.0)*exp(sdb1*( Vdb+V))*cdb;
    alphaf_inf = cfa/( exp(-sfa2*( shiftf-V-Vfa))+1.0)*exp(-sfa1*( shiftf-V-Vfa));
    betaf_inf = cfb*exp(-sfb1*( shiftf-Vfb-V))/( exp(-sfb2*( shiftf-Vfb-V))+1.0);
    alphaf_tau = cfa*exp(sfa1*( V+Vfa))/( exp(sfa2*( V+Vfa))+1.0);
    betaf_tau = cfb/( exp(sfb2*( Vfb+V))+1.0)*exp(sfb1*( Vfb+V));
    alphax = 1.0/( exp(( Vxa+V)*sxa2)+1.0)*cxa*exp(( Vxa+V)*sxa1);
    betax = 1.0/( exp(( Vxb+V)*sxb2)+1.0)*exp(( Vxb+V)*sxb1)*cxb;
    taud = 1.0/( alphad_tau+betad_tau);
    tauf = 1.0/( alphaf_tau+betaf_tau);
    taux = 1.0/( alphax+betax);
    dinf = 1.0/( betad_inf+alphad_inf)*alphad_inf;
    finf = alphaf_inf/( alphaf_inf+betaf_inf);
    xinf = alphax/( alphax+betax);
    xi = cxi/( Vxi1+V)/exp(sxi*( Vxi2+V))*( exp(( Vxi1+V)*sxi)-1.0);
    alphaK1 = 1.0/( exp(-( VK1-V+5.9215000000000003e+01)*sK1a)+1.0)*cK1a;
    betaK1 = 1.0/( exp(-( VK1-V-4.7530000000000001e+00)*sK1b3)+1.0)*( exp(-sK1b2*( VK1-V+5.9430999999999995e+02))+cK1b*exp(-sK1b1*( VK1-V-5.4760000000000000e+00)));
    K1inf = alphaK1/( alphaK1+betaK1);
    Kp = 1.0/( exp(sKp*( VKp-V))+1.0);
    ICa = d*( V-VCa)*f*gCa;
    IK = -( VK-V)*gK*x*xi;
    IK1 = -( VK1-V)*K1inf*gK1;
    IKp = -( VK1-V)*Kp*gKp;
    Ib = gb*( Vb+V);

    /*
     *  The vector field
     */

    f_[0] = -( 1.0/C*(IK1+IKp+ICa+Ib+IK))*T;
    f_[1] = -1.0/C*( d-dinf)*T/taud;
    f_[2] = 1.0/tauf*T*( finf-f);
    f_[3] = T/taux*( xinf-x);

    if (ijac_ == 0) {
        return 0;
    }

    return 0;
}
/*
 *  STPNT  Gives a starting point
 */

int stpnt(integer ndim_, doublereal t_, doublereal *u_, doublereal *par_)
{
    const double Ki = 145.0;
    const double Nao = 140.0;
    const double Nai = 18.0;
    const double PRNaK = 1.8329999999999999e-02;
    const double R = 8.3144626181532395e+00;
    const double Kelvin = 3.1014999999999998e+02;
    const double Faraday = 9.6485332900000003e+01;
    const double cda = 9.5000000000000001e-02;
    const double cdb = 7.0000000000000007e-02;
    const double cfa = 1.2000000000000000e-02;
    const double cfb = 6.4999999999999997e-03;
    const double cxa = 5.0000000000000001e-04;
    const double cxb = 1.2999999999999999e-03;
    const double cxi = 2.8370000000000002e+00;
    const double cK1a = 1.0200000000000000e+00;
    const double cK1b = 4.9124000000000001e-01;
    const double Vda = -5.0000000000000000e+00;
    const double Vdb = 4.4000000000000000e+01;
    const double Vfa = 2.8000000000000000e+01;
    const double Vfb = 3.0000000000000000e+01;
    const double Vxa = 5.0000000000000000e+01;
    const double Vxb = 2.0000000000000000e+01;
    const double Vxi1 = 7.7000000000000000e+01;
    const double Vxi2 = 3.5000000000000000e+01;
    const double sda1 = -1.0000000000000000e-02;
    const double sda2 = -7.1999999999999995e-02;
    const double sdb1 = -1.7000000000000001e-02;
    const double sdb2 = 5.0000000000000003e-02;
    const double sfa1 = -8.0000000000000002e-03;
    const double sfa2 = 1.4999999999999999e-01;
    const double sfb1 = -2.0000000000000000e-02;
    const double sfb2 = -2.0000000000000001e-01;
    const double sxa1 = 8.3000000000000004e-02;
    const double sxa2 = 5.7000000000000002e-02;
    const double sxb1 = -5.9999999999999998e-02;
    const double sxb2 = -4.0000000000000001e-02;
    const double sxi = 4.0000000000000001e-02;
    const double sK1a = 2.3849999999999999e-01;
    const double sK1b1 = 8.0320000000000003e-02;
    const double sK1b2 = 6.1749999999999999e-02;
    const double sK1b3 = -5.1429999999999998e-01;
    const double sKp = 1.6722408026755853e-01;
    const double gK1w = 6.0470000000000002e-01;
    const double gKp = 1.8300000000000000e-02;
    const double gb = 3.9210000000000002e-02;
    const double VKp = 7.4880000000000004e+00;
    const double Vb = 5.9869999999999997e+01;
    double V, d, f, x;
    double C, Ko, shiftd, shiftf, gKw, gCa, VCa, T;

    /* Change the parameter values and the starting point to correct values! */

    C = 1.0;
    Ko = 5.4000000000000004e+00;
    shiftd = -3.4;
    shiftf = 3.4;
    gKw = 2.8199999999999997e-01;
    gCa = 8.9999999999999997e-02;
    VCa = 8.0000000000000000e+01;

    T = 0;

	/*folded node?*/
    V = -16.0842;
    d = 0.777308;
    f = 0.560897;
    x = 0.510548;

    par_[0] = C;
    par_[1] = Ko;
    par_[2] = shiftd;
    par_[3] = shiftf;
    par_[4] = gKw;
    par_[5] = gCa;
    par_[6] = VCa;
    par_[10] = T;

    u_[0] = V;
    u_[1] = d;
    u_[2] = f;
    u_[3] = x;

   /* boundary condition params */

    par_[7] = u_[0]; /* V(0) */
    par_[8] = u_[1]; /* d(0) */
    par_[9] = u_[2]; /* f(0) */
    par_[11] = u_[3]; /* x(0) */
    par_[12] = u_[0]; /* V(1) */
    par_[13] = u_[1]; /* d(1) */
    /*par_[14] = u_[2]; /* f(1) */
    par_[15] = u_[3]; /* x(1) */

    return 0;
}


/*
 *  BCND  Defines the boundary conditions
 */

int bcnd(integer ndim_, const doublereal *par_, const integer *icp_,
         integer nbc_, const doublereal *u0_, const doublereal *u1_, integer ijac_,
         doublereal *fb_, doublereal *dbc_)
{  
    const double Ki = 145.0;
    const double Nao = 140.0;
    const double Nai = 18.0;
    const double PRNaK = 1.8329999999999999e-02;
    const double R = 8.3144626181532395e+00;
    const double Kelvin = 3.1014999999999998e+02;
    const double Faraday = 9.6485332900000003e+01;
    const double cda = 9.5000000000000001e-02;
    const double cdb = 7.0000000000000007e-02;
    const double cfa = 1.2000000000000000e-02;
    const double cfb = 6.4999999999999997e-03;
    const double cxa = 5.0000000000000001e-04;
    const double cxb = 1.2999999999999999e-03;
    const double cxi = 2.8370000000000002e+00;
    const double cK1a = 1.0200000000000000e+00;
    const double cK1b = 4.9124000000000001e-01;
    const double Vda = -5.0000000000000000e+00;
    const double Vdb = 4.4000000000000000e+01;
    const double Vfa = 2.8000000000000000e+01;
    const double Vfb = 3.0000000000000000e+01;
    const double Vxa = 5.0000000000000000e+01;
    const double Vxb = 2.0000000000000000e+01;
    const double Vxi1 = 7.7000000000000000e+01;
    const double Vxi2 = 3.5000000000000000e+01;
    const double sda1 = -1.0000000000000000e-02;
    const double sda2 = -7.1999999999999995e-02;
    const double sdb1 = -1.7000000000000001e-02;
    const double sdb2 = 5.0000000000000003e-02;
    const double sfa1 = -8.0000000000000002e-03;
    const double sfa2 = 1.4999999999999999e-01;
    const double sfb1 = -2.0000000000000000e-02;
    const double sfb2 = -2.0000000000000001e-01;
    const double sxa1 = 8.3000000000000004e-02;
    const double sxa2 = 5.7000000000000002e-02;
    const double sxb1 = -5.9999999999999998e-02;
    const double sxb2 = -4.0000000000000001e-02;
    const double sxi = 4.0000000000000001e-02;
    const double sK1a = 2.3849999999999999e-01;
    const double sK1b1 = 8.0320000000000003e-02;
    const double sK1b2 = 6.1749999999999999e-02;
    const double sK1b3 = -5.1429999999999998e-01;
    const double sKp = 1.6722408026755853e-01;
    const double gK1w = 6.0470000000000002e-01;
    const double gKp = 1.8300000000000000e-02;
    const double gb = 3.9210000000000002e-02;
    const double VKp = 7.4880000000000004e+00;
    const double Vb = 5.9869999999999997e+01;
    double V0, d0, f0, x0, V1, d1, f1, x1;
    double C, Ko, shiftd, shiftf, gKw, gCa, VCa, T;
    double gK, gK1, VK, VK1, alphad_inf, betad_inf, alphad_tau, betad_tau, alphaf_inf, betaf_inf, alphaf_tau, betaf_tau, alphax, betax, taud, tauf, taux, dinf, finf, xinf, xi, alphaK1, betaK1, K1inf, Kp, ICa, IK, IK1, IKp, Ib;
    double dinfalpha, dalphad, dinfbeta, dbetad, ddinfdV, dxidV, dalphaK1, K1infbeta, dbetaK1, dK1dV, dKpdV, dFdV; 

    /* boundary points */

    V0          = u0_[0];
    d0          = u0_[1];
    f0          = u0_[2];
    x0          = u0_[3];

    V1          = u1_[0];
    d1          = u1_[1];
    f1          = u1_[2];
    x1          = u1_[3];

    /* parameters */

    C          = par_[0];
    Ko         = par_[1];
    shiftd     = par_[2];
    shiftf     = par_[3];
    gKw        = par_[4];
    gCa        = par_[5];
    VCa        = par_[6];
    T          = par_[10];

    /* expressions */

    gK = 4.3033148291193524e-01*gKw*pow(Ko,(1.0/2.0));
    gK1 = 4.3033148291193524e-01*pow(Ko,(1.0/2.0))*gK1w;
    VK = 1.0/Faraday*log(( PRNaK*Nao+Ko)/( Ki+PRNaK*Nai))*R*Kelvin;
    VK1 = 1.0/Faraday*R*log(1.0/Ki*Ko)*Kelvin;

    alphad_inf = cda/( exp(sda2*( Vda-shiftd+V0))+1.0)*exp(sda1*( Vda-shiftd+V0));
    betad_inf = 1.0/( exp(( Vdb-shiftd+V0)*sdb2)+1.0)*exp(( Vdb-shiftd+V0)*sdb1)*cdb;

    alphad_tau = exp(( Vda+V0)*sda1)/( exp(sda2*( Vda+V0))+1.0)*cda;
    betad_tau = 1.0/( exp(sdb2*( Vdb+V0))+1.0)*exp(sdb1*( Vdb+V0))*cdb;

    alphaf_inf = cfa/( exp(-sfa2*( shiftf-V0-Vfa))+1.0)*exp(-sfa1*( shiftf-V0-Vfa));
    betaf_inf = cfb*exp(-sfb1*( shiftf-Vfb-V0))/( exp(-sfb2*( shiftf-Vfb-V0))+1.0);

    alphaf_tau = cfa*exp(sfa1*( V0+Vfa))/( exp(sfa2*( V0+Vfa))+1.0);
    betaf_tau = cfb/( exp(sfb2*( Vfb+V0))+1.0)*exp(sfb1*( Vfb+V0));

    alphax = 1.0/( exp(( Vxa+V0)*sxa2)+1.0)*cxa*exp(( Vxa+V0)*sxa1);
    betax = 1.0/( exp(( Vxb+V0)*sxb2)+1.0)*exp(( Vxb+V0)*sxb1)*cxb;

    taud = 1.0/( alphad_tau+betad_tau);
    tauf = 1.0/( alphaf_tau+betaf_tau);
    taux = 1.0/( alphax+betax);

    dinf = 1.0/( betad_inf+alphad_inf)*alphad_inf;
    finf = alphaf_inf/( alphaf_inf+betaf_inf);
    xinf = alphax/( alphax+betax);

    xi = cxi/( Vxi1+V0)/exp(sxi*( Vxi2+V0))*( exp(( Vxi1+V0)*sxi)-1.0);

    alphaK1 = 1.0/( exp(-( VK1-V0+5.9215000000000003e+01)*sK1a)+1.0)*cK1a;
    betaK1 = 1.0/( exp(-( VK1-V0-4.7530000000000001e+00)*sK1b3)+1.0)*( exp(-sK1b2*( VK1-V0+5.9430999999999995e+02))+cK1b*exp(-sK1b1*( VK1-V0-5.4760000000000000e+00)));
    K1inf = alphaK1/( alphaK1+betaK1);

    Kp = 1.0/( exp(sKp*( VKp-V0))+1.0);

    ICa = d0*( V0-VCa)*f0*gCa;
    IK = -( VK-V0)*gK*x0*xi;
    IK1 = -( VK1-V0)*K1inf*gK1;
    IKp = -( VK1-V0)*Kp*gKp;
    Ib = gb*( Vb+V0);

    /* expressions used to define det(J) of the fast subsystem */

    dinfalpha = 1.0/( exp(-sda2*( Vda+V0-shiftd))+1.0);
    dalphad = -( dinfalpha*sda2-sda1)*alphad_inf;
    dinfbeta = 1.0/( exp(-sdb2*( Vdb+V0-shiftd))+1.0);
    dbetad = -betad_inf*( dinfbeta*sdb2-sdb1);
    ddinfdV = (1.0/( alphad_inf+betad_inf))*( dalphad-( dbetad+dalphad)*dinf);
    dxidV = -( xi-cxi/exp(sxi*( Vxi2+V0))*sxi)/( Vxi1+V0);
    dalphaK1 = ( 1.0/cK1a*alphaK1-1.0)*alphaK1*sK1a;
    K1infbeta = 1.0/( exp(( VK1-V0-4.7530000000000001e+00)*sK1b3)+1.0);
    dbetaK1 = -betaK1*K1infbeta*sK1b3+( exp(-sK1b2*( VK1-V0+5.9430999999999995e+02))*sK1b2+cK1b*sK1b1*exp(-sK1b1*( VK1-V0-5.4760000000000000e+00)))/( exp(-( VK1-V0-4.7530000000000001e+00)*sK1b3)+1.0);
    dK1dV = -( ( dbetaK1+dalphaK1)*K1inf-dalphaK1)/( betaK1+alphaK1);
    dKpdV = -sKp*Kp*( Kp-1.0);
    
    dFdV = /*ICa*/ gCa*ddinfdV*f0*(V0-VCa)+gCa*dinf*f0 + /*IK*/ gK*dxidV*x0*(V0-VK)+gK*xi*x0 + /*IK1*/ gK1*dK1dV*(V0-VK1)+gK1*K1inf + 
	   /*IKp*/ gKp*dKpdV*(V0-VK1)+gKp*Kp + /*Ib*/ gb;

    /* critical manifold fb_[0]*/

    fb_[0] = ICa + IK + IK1 + IKp + Ib;

    fb_[1] = V0 - par_[7];
    fb_[2] = d0 - par_[8];
    fb_[3] = f0 - par_[9];
    fb_[4] = x0 - par_[11];
    fb_[5] = V1 - par_[12];
    
    /* d = dinf(V) */

    fb_[6] = d0-dinf;
    
    if(nbc_ == 7){return 0;}

    /* fb_[0] and fb_[7] together define the fold curve */    

    fb_[7] = dFdV;
 
    return 0;
}

/*
 *  ICND  Defines the integral conditions
 */

int icnd(integer ndim_, const doublereal *par_, const integer *icp_,
         integer nint_, const doublereal *u_, const doublereal *uold_,
         const doublereal *udot_, const doublereal *upold_, integer ijac_,
         doublereal *fi_, doublereal *dint_)
{
    return 0;
}

/*
 *  FOPT
 */

int fopt(integer ndim_, const doublereal *u_, const integer *icp_,
         const doublereal *par_, integer ijac_,
         doublereal *fs_, doublereal *dfdu_, doublereal *dfdp_)
{
    return 0;
}

/*
 *  PVLS
 */

int pvls(integer ndim_, const doublereal *u_, doublereal *par_)
{   

    par_[13] = getp("BV1", 2, u_); /* d(1) */
    par_[14] = getp("BV1", 3, u_); /* f(1) */
    par_[15] = getp("BV1", 4, u_); /* x(1) */
    
    return 0;
}
